type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Distinguished Paper Award"
subtitle = "USENIX Security"
date = "2026"
content = ""

[[items]]
title = "Presidential Scholarship"
subtitle = "Peking University"
date = "2026"
content = ""

[[items]]
title = "Best Demo Runner-Up"
subtitle = "ACM MobiCom"
date = "2025"
content = ""

[[items]]
title = "Merit Student Pacesetter"
subtitle = "Peking University"
date = "2023"
content = ""

[[items]]
title = "Huatai Science and Technology Scholarship"
subtitle = "Peking University"
date = "2023"
content = ""

[[items]]
title = "Merit Student Pacesetter"
subtitle = "Peking University"
date = "2022"
content = ""

[[items]]
title = "Huatai Science and Technology Scholarship"
subtitle = "Peking University"
date = "2022"
content = ""

[[items]]
title = "Award for Academic Excellents"
subtitle = "Peking University"
date = "2021"
content = ""

[[items]]
title = "The Third Prize of Peking University Scholarship"
subtitle = "Peking University"
date = "2021"
content = ""
